contacto/urls.py
from django.urls import path
from contacto import views
from contacto.views import Contacto
from contacto.views import MensajeEnviado


urlpatterns = [
    path('', Contacto.as_view(), name='contacto'),
    path('mensaje_enviado/', MensajeEnviado.as_view(), name='mensaje_enviado'),
]

proy_service/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('', include('servicios_board.urls')),
    # Siguiente linea agregada para utilizar django-registration-redux
    # path('accounts/', include('registration.backends.default.urls'), name="rr"),
    path('admin/', admin.site.urls),    
    path('usuarios/', include('usuarios.urls')),
    path('store/', include('store.urls')),
    #path('captcha/', include('captcha.urls')),
    path('contacto/', include('contacto.urls')),
    path('carrito/', include('carrito.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    

store/urls.py
from django.contrib import admin
from django.urls import path
from store.views import index
from store.views import index2
from store.views import ver_imagen
from store.views import VerProducto
from store.views import VerProductoLs
from store.views import barra_busqueda_ajax
from store.views import BuscarProducto
from store.views import BuscarProducto2
from store.quitar import quitar
from store.crear_localstorage import crear_localstorage
from store import views_agregar_item
from store import views_agregar_items_carro


urlpatterns = [
    path('construccion/', index2, name='index2'),
    path('', index, name='store_index'),
    path('<int:producto_id>/ver-producto/', ver_imagen, name='ver-producto'),
    path('<int:producto_id>/ver/', VerProducto.as_view() , name='ver'),
    # de aca en adelante es para funcionar con el tema de localStorage (jquery y ajax)
    path('<int:producto_id>/ver-producto-ls/', VerProductoLs.as_view(), name='ver-producto-ls'),
    path("agregar_item/", views_agregar_item.agregar_item, name="agregar_item"),
    path("agregar_items_carro/", views_agregar_items_carro.agregar_items_carro, name="agregar_items_carro"),
    path("busqueda_ajax/", barra_busqueda_ajax, name="busqueda_ajax"),
    path("buscar_producto/", BuscarProducto.as_view(), name="buscar_producto"),
    path("buscar_producto2/", BuscarProducto2.as_view(), name="buscar_producto2"),
    path("quitar_producto/", quitar, name="quitar_producto"),
    path("crear_ls/", crear_localstorage, name="crear_ls"),

]

contacto/models.py
from django.db import models
from datetime import datetime
from django.utils.html import format_html

# Create your models here.
class ContactoConsulta(models.Model):
    
    CONTESTADA = "Contestada"
    NOCONTESTADA = "No Contestada"
    ENPROCESO = "En Proceso" 
    ESTADOS = (
            (CONTESTADA, "Contestada"),
            (NOCONTESTADA, "No Contestada"),
            (ENPROCESO,"En Proceso"),
    )

    nombre = models.CharField(max_length=50, null=False)
    descripcion = models.TextField(blank=False, null=False)
    email = models.EmailField(max_length=50, blank=False, null=False)
    estado_respuesta = models.CharField(max_length=50, choices=ESTADOS, default=NOCONTESTADA)
    telefono = models.CharField(max_length=50, null=False, blank=False)
    fecha = models.DateField(default=datetime.now, null=False, blank=True, editable=True)
    
    def __str__(self) -> str:
        return self.nombre
    
    def estado_de_respuesta(self):
        if self.estado_respuesta == "Contestada":
            return format_html('<span style="background-color:#0a0; color: #fff; padding:5px;">{}</span>', self.estado_respuesta, )
            
        elif self.estado_respuesta == "No Contestada":
            return format_html("<span style='background-color:#a00; color:#fff; padding:5px;'>{}</span>", self.estado_respuesta,)
 
        elif self.estado_respuesta == "En Proceso":
            return format_html("<span style='background-color:#AEB404; color:#fff; padding:5px;'>{}</span>", self.estado_respuesta,)

        
        
    
class ContactoRespuesta(models.Model):
        
    consulta = models.ForeignKey(ContactoConsulta, blank=False, null=True, on_delete=models.CASCADE)
    respuesta = models.TextField()
    fecha = models.DateField(default=datetime.now, blank=True, null=False, editable=True)
    

    def crear_mensaje(self):
        
        consulta_cambio_estado = ContactoConsulta.objects.get(id=self.consulta.id)
        consulta_cambio_estado.estado_respuesta = "Contestada"
        consulta_cambio_estado.save()

        #aqui va la logica de envio de mail, sms o lo que sea de la respuesta 
        
    def save(self, *args, **kwargs):
        self.crear_mensaje()
        force_update = False
        if self.id:
            force_update = True
        super(ContactoRespuesta, self).save(force_update=force_update)
        
        

contacto/forms.py
from typing import Any, Dict, Mapping, Optional, Type, Union
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms import ModelForm
from django.forms.utils import ErrorList
from contacto.models import ContactoConsulta
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox

class ConsultaForm(ModelForm):
    
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())
    
    class Meta:
        model = ContactoConsulta
        fields = [
            'nombre',
            'descripcion',
            'email',
            'telefono',
        ]
    
    def send_email(self,):
        
        nombre = self.cleaned_data['nombre']
        descripcion = self.cleaned_data['descripcion']
        email = self.cleaned_data['email']
        #estado_respuesta = self.cleaned_data[estado_respuesta]
        telefono = self.cleaned_data['telefono']
        #fecha_consulta = self.cleaned_data[fecha_consulta]
        
        # logica para el envio de email

contacto/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic import FormView
from contacto.models import ContactoConsulta
from contacto.forms import ConsultaForm

# Create your views here.
class Contacto(FormView):
    
    template_name = 'contacto/contacto.html'
    form_class = ConsultaForm
    success_url = 'mensaje_enviado'#contacto/succes.html'
    
    
    def form_valid(self, form):
        form.save()
        form.send_email()
        return super().form_valid(form)
        
class MensajeEnviado(View):
    template = 'contacto/mensaje_enviado.html'
    
    def get(self, request):
        
        params = {}
        params["Mensaje"] = "Aca va un mensaje de prueba"
        return render(request, self.template, params)

templates/contacto/__contacto.html
{% extends "layout.html" %}
{% block title %}Contacto{% endblock %}
{% load static %}
{% load i18n %}
{% block contacto %}
<!-- ---------------------------------------------------------------------------
-------------- 
------------------------------------------------------------------------------->
 <div class="container">

 
</div> 
     
 <div class="container-fluid"   >
    <div class="row reflexion justify-content-around align-items-center border" style="padding-top:20px;">   
        <div class="col-12 col-md-5 contacto_form" style="padding-bottom:15px;">
                    <h1 class="h1juan" style="padding-left:15px;">Contacto</h1>    
                    <form id="contact" action="" method="post" class="col-xs-12">{% csrf_token %} 		
                        <div class="col-12 form-group" >
                            {{form }}
                        </div> 
                        <div class="row justify-content-between">
                            <div class="col-4"></div>
                            <div class="col-4" style="padding-right:30px;">
                                <button type="submit"  class=" col-12 btn btn-danger">Enviar</button>
                            </div>
                        </div>                        
                    </form>
        </div>    
         
     </div>
 </div>  

    
<section class="container-fluid ">
    <div class="row" style="padding-top:10px; ">
        <div class="col-12" style="padding:0px;  ">
           <br/> 
        </div>
    </div>
</section>
   
  



{% endblock %}
{% block javascript %}
<script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script> 
<script type="text/javascript" src="{% static 'js/juan_ajax.js' %}"></script>

 
     

	<script>
		$("#id_fecha").css({'display':'none'});
		//$("#id_fecha").parent().find("label").css({'display':'none'});
		$("#id_estado_respuesta").css({'display':'none'});
		$("#id_estado_respuesta").parent().find("label").css({'display':'none'});
		
		
		$("#formulario_contacto li").css({'list-style':'none'});
 
		//$("#formulario_contacto li label").css({'width':"100%", 'text-align':'center',});
		//$("#formulario_contacto li input").css({'width':"100%", 'text-align':'center',});

		$("input").css({'width':"100%", 'text-align':'center', 'margin-bottom':'7px'});
		$("textarea").css({'width':"100%", 'text-align':'center',});


		$("#id_nombre").attr("placeholder", "Nombre");
		$("#id_descripcion").attr("placeholder", "Descripcion");
		$("#id_mail").attr("placeholder", "Mail");
		$("#id_telefono").attr("placeholder", "Teléfono");
		$("#id_captcha_1").attr("placeholder", "Captcha");
	</script>
	
	
	
	
{% endblock %}

templates/contacto/contacto.html
{% extends "layout.html" %}
{% block title %}Contacto{% endblock %}
{% load static %}
{% load i18n %}
{% block body %}


{% comment %} <div class="container-fluid"   >
   <div class="row reflexion justify-content-around align-items-center border" style="padding-top:20px;">   
       <div class="col-12 col-md-5 contacto_form" style="padding-bottom:15px;">
            <h1 class="h1juan" style="padding-left:15px;">Contacto</h1>     {% endcomment %}

<div class="fluid py-3">
    <div class="card" style="background-color: #F0F0F0; border-color: #25A2C7; box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
        <div class="card-body">
                    <form id="contact" action="" method="POST">{% csrf_token %}
                      <center>
                      <img class="mb-3" src="{% static 'img/message2.png' %}" alt="" width="70" height="70">
                      <h1 class="h3 mb-3 fw-normal">Formulario de Contacto</h1>
                      {% for message in messages %}
                      <div class="alert alert-danger" role="alert">
                        <i class="fa-solid fa-circle-exclamation fa-beat"></i>
                         {{message}}
                      </div>
                      {% endfor %}
                    </center>
                      <div class="form-floating mb-3">
                      {% comment %} <input type="text" class="form-control" id="floatingInput" placeholder="Nombre"{{form.nombre}}</>
                      <label for="floatingInput"><i class="fa-solid fa-user"></i> Nombre de Usuario</label>
                      </div> {% endcomment %}
                        <input type="Name" class="form-control" id="floatingInput" placeholder="Nombre" {{form.nombre}}
                        <label for="floatingInput" class="form-label"><i class="fa-solid fa-user"></i> Nombre</label>
                      </div>
                      <div class="form-floating mb-3">
                        <input type="tel" pattern="[0-9]+[-]*[0-9]+[-]*[0-9]*[-]*[0-9]*" class="form-control" id="floatingInput" placeholder="Telefono" {{form.telefono}}
                        <label for="floatingInput" class="form-label"><i class="fa-solid fa-phone"></i> Telefono</label>
                      </div>
                            
                      <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="floatingInput" placeholder="Email" {{form.email}}
                        <label for="floatingInput" class="form-label"><i class="fa-solid fa-envelope"></i> Email</label>
                      </div>
                      <div class="form-floating mb-3">
                        <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Mensaje" style="height: 150px" {{form.descripcion}}</textarea>
                        <label for="floatingInput" class="form-label"><i class="fa-solid fa-comment"></i> Mensaje</label>
                      </div>
                      <center>
                      <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label"></label>
                        {{form.captcha}}
                      </div>
                      <br>
                      <button class="btn btn-lg btn-primary" type="submit">
                        Enviar
                      </button>
                        <br>
                        <br>
                      <div class="border-top pt-3">
                        <small class="text-muted">
                          No Tenes Cuenta? <a class="ml-2" href="{% url 'registro' %}">Registrate Ahora</a>
                        </small><br>
                        <small class="text-muted">
                          <a href="/">Olvidaste tu contraseña?</a>
                        </small>
                      </center>
                      </div>
                      {% comment %} <div class="border-top pt-3">
                        <small class="text-muted">
                          HM-NET © 2001–2023
                        </small><br>
                      </div> {% endcomment %}
                    </form>
      
 		                        
                        {% comment %} <div class="form-outline mb-4">
                                <button type="submit"  class=" col-12 btn btn-danger">Enviar</button>
                            </div>
                        </div>                         {% endcomment %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>  










            {% comment %} <div class="fluid py-3">
    <div class="card" style="background-color: antiquewhite;">
        <div class="card-body">
                    <form id="contact" action="" method="POST">{% csrf_token %}
                      <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label"></label>
                        <input type="Name" class="form-control" id="floatingInput" placeholder="Nombre" {{form.nombre}}
                      </div>
                      <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label"></label>
                        <input type="Tel" class="form-control" id="exampleFormControlInput1" placeholder="Telefono" {{form.telefono}}
                      </div>
                            
                      <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label"></label>
                        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="Email" {{form.email}}
                      </div>
                      <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label"></label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Mensaje" {{form.descripcion}}</textarea>
                      </div>
                      <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label"></label>
                        {{form.captcha}}
                      </div>

 		                        
                        <div class="form-outline mb-4">
                                <button type="submit"  class=" col-12 btn btn-danger">Enviar</button>
                            </div>
                        </div>                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>   {% endcomment %}
{% comment %} 
<form id="contact" action="" method="post">{% csrf_token %} >
    
    <!-- Name input -->
    <div class="row">
        <div class="col">
          <input type="text" class="form-control" placeholder="Nombre" aria-label="Nombre" {{form.nombre}}
            
        </div>
        <div class="col">
          <input type="text" class="form-control" placeholder="Email" aria-label="Email" {{form.email}}
        </div>
        <div class="col">
        <input type="text" class="form-control" placeholder="Telefono" aria-label="Telefono" {{form.telefono}}
        </div>
        <div class="col">
            <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea"{{form.descripcion}}</textarea>
            <label for="floatingTextarea">Consulta</label>
          </div>
    </div>
    <!-- Checkbox -->
    <div class="form-check d-flex justify-content-center mb-4">
      <input class="form-check-input me-2" type="checkbox" value="" id="form4Example4" checked />
      <label class="form-check-label" for="form4Example4">
        Send me a copy of this message
      </label>
    </div>
  
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4" action="" method="post"{% csrf_token %}>Send</button>
  </form> {% endcomment %}
   
{% comment %} <section class="container-fluid ">
    <div class="row" style="padding-top:10px; ">
        <div class="col-12" style="padding:0px;  ">
           <br/> 
        </div>
    </div>
</section> {% endcomment %}
   
  



{% endblock %}
{% block javascript %}
{% comment %} <script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script> 
<script type="text/javascript" src="{% static 'js/juan_ajax.js' %}"></script>

 
     

	<script>
		$("#id_fecha").css({'display':'none'});
		//$("#id_fecha").parent().find("label").css({'display':'none'});
		$("#id_estado_respuesta").css({'display':'none'});
		$("#id_estado_respuesta").parent().find("label").css({'display':'none'});
		
		
		$("#formulario_contacto li").css({'list-style':'none'});
 
		//$("#formulario_contacto li label").css({'width':"100%", 'text-align':'center',});
		//$("#formulario_contacto li input").css({'width':"100%", 'text-align':'center',});

		$("input").css({'width':"100%", 'text-align':'center', 'margin-bottom':'7px'});
		$("textarea").css({'width':"100%", 'text-align':'center',});


		$("#id_nombre").attr("placeholder", "Nombre");
		$("#id_descripcion").attr("placeholder", "Descripcion");
		$("#id_mail").attr("placeholder", "Mail");
		$("#id_telefono").attr("placeholder", "Teléfono");
		$("#id_captcha_1").attr("placeholder", "Captcha");
	</script>
	 {% endcomment %}
	
	
	
{% endblock %}

templates/contacto/mensaje_enviado.html
{% extends "layout.html" %}
{% block title %}ENSAJE ENVIADO{% endblock %}
{% load static %}
{% load i18n %}
{% block body %}


<div class="container-fluid  "   >
    <div class="row reflexion justify-content-center align-items-center  " style="padding-top:20px;">   
        <div class="col-8  " style="padding-top:40px; padding-bottom: 40px;">
            <div>
                <center>
                    <h1 style="color:red;">MUCHAS GRACIAS!<i class="fas fa-star"></i></h1>
                    <p>En breve<b>se van a contactar con vos</b> para coordinar!</p>
                    <p>Mientras tanto te invitamos a ver todos nuestros productos en la <b style="color:red;">tienda minorista</b></p>
 
                </center>    
            </div>
        </div>  
     </div>
 </div>
  

    
<section class="container-fluid ">
    <div class="row" style="padding-top:10px; ">
        <div class="col-12" style="padding:0px;  ">
           <br/> 
        </div>
    </div>
</section>
   
  



{% endblock %}
{% block javascript %}
    <script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
    <script type="text/javascript" src="{% static 'js/juan_ajax.js' %} " ></script>
{% endblock %}