proy_service/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('', include('servicios_board.urls')),
    # Siguiente linea agregada para utilizar django-registration-redux
    # path('accounts/', include('registration.backends.default.urls'), name="rr"),
    path('admin/', admin.site.urls),    
    path('usuarios/', include('usuarios.urls')),
    path('store/', include('store.urls')),
    #path('captcha/', include('captcha.urls')),
    path('contacto/', include('contacto.urls')),
    path('carrito/', include('carrito.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    

store/urls.py
from django.contrib import admin
from django.urls import path
from store.views import index
from store.views import index2
from store.views import ver_imagen
from store.views import VerProducto
from store.views import VerProductoLs
from store.views import barra_busqueda_ajax
from store.views import BuscarProducto
from store.views import BuscarProducto2
from store.quitar import quitar
from store.crear_localstorage import crear_localstorage
from store import views_agregar_item
from store import views_agregar_items_carro


urlpatterns = [
    path('construccion/', index2, name='index2'),
    path('', index, name='store_index'),
    path('<int:producto_id>/ver-producto/', ver_imagen, name='ver-producto'),
    path('<int:producto_id>/ver/', VerProducto.as_view() , name='ver'),
    # de aca en adelante es para funcionar con el tema de localStorage (jquery y ajax)
    path('<int:producto_id>/ver-producto-ls/', VerProductoLs.as_view(), name='ver-producto-ls'),
    path("agregar_item/", views_agregar_item.agregar_item, name="agregar_item"),
    path("agregar_items_carro/", views_agregar_items_carro.agregar_items_carro, name="agregar_items_carro"),
    path("busqueda_ajax/", barra_busqueda_ajax, name="busqueda_ajax"),
    path("buscar_producto/", BuscarProducto.as_view(), name="buscar_producto"),
    path("buscar_producto2/", BuscarProducto2.as_view(), name="buscar_producto2"),
    path("quitar_producto/", quitar, name="quitar_producto"),
    path("crear_ls/", crear_localstorage, name="crear_ls"),

]

templates/store/urls.py
from django.contrib import admin
from django.urls import path
from store.views import index
from store.views import index2
from store.views import ver_imagen
from store.views import VerProducto
from store.views import VerProductoLs
from store.views import barra_busqueda_ajax
from store.views import BuscarProducto
from store.views import BuscarProducto2
from store import views_agregar_item


urlpatterns = [
    path('construccion/', index2, name='index2'),
    path('', index, name='store_index'),
    path('<int:producto_id>/ver-producto/', ver_imagen, name='ver-producto'),
    path('<int:producto_id>/ver/', VerProducto.as_view() , name='ver'),
    # de aca en adelante es para funcionar con el tema de localStorage (jquery y ajax)
    path('<int:producto_id>/ver-producto-ls/', VerProductoLs.as_view(), name='ver-producto-ls'),
    path("agregar_item/", views_agregar_item.agregar_item, name="agregar_item"),
    path("busqueda_ajax/", barra_busqueda_ajax, name="busqueda_ajax"),
    path("buscar_producto/", BuscarProducto.as_view(), name="buscar_producto"),
    path("buscar_producto2/", BuscarProducto2.as_view(), name="buscar_producto2"),
]

store/models.py
from django.db import models
from django.utils.html import format_html


# Create your models here.


class Store(models.Model):

    no_pub = "No Publicado"
    pub = "Publicado"
    borr = "Borrador"
    ESTADO_PRODUCTO = (
        (no_pub, "No Publicado"),
        (pub, "Publicado"),
        (borr, "Borrador"),
    )

    filtro80 = "Filtro 80x80mm"
    filtro120 = "Filtro 120x120mm"
    filtro140 = "Filtro 140x140mm"
    hdd = "Disco Rigido"
    software = "Software"
    dir_lister = "Directories Lister"
    hm_meta = "Meta Data Extractor"
    LOS_PRODUCTOS = (
        (filtro80, "Filtro 80x80mm"),
        (filtro120, "Filtro 120x120mm"),
        (filtro140, "Filtro 140x140mm"),
        (hdd, "Disco Rigido"),
        (software, "Software"),
        (dir_lister, "Directories Lister"),
        (hm_meta, "Meta Data Extractor"),
    )



    producto = models.CharField(max_length=60, choices=LOS_PRODUCTOS)
    descripcion_corta = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=300)
    fecha_publicacion = models.DateField('Fecha de Publicacion')
    estado_actual = models.CharField(max_length=30, choices=ESTADO_PRODUCTO, default="No Publicado")
    precio = models.IntegerField("Precio AR$")
    cantidad_disponible = models.IntegerField('Unidades Disponibles')
    imagen = models.ImageField(upload_to="producto/%Y/%m/%d", blank=True, null=True) 
    stock_valor = models.IntegerField("Valor Stock AR$", null=True)
    
    # categoria = models.ManyToManyField(Categoria)

    def __str__(self):
        return str(self.producto) + " - " + str(self.cantidad_disponible) + " - "+ str(self.estado_actual)      #sobreescrito por list_display


    def tipo_de_estado(self):
        if self.estado_actual == "Publicado":
            return format_html('<span style="background-color: #31B404; padding: 2px; font-weight: bold;">{}</span>', self.estado_actual, )

        elif self.estado_actual == "Borrador":
            return format_html('<span style="background-color: #AEB404; padding: 2px; font-weight: bold;">{}</span>', self.estado_actual, )

        elif self.estado_actual == "No Publicado":
            return format_html('<span style="background-color: #FF0000; padding: 2px; font-weight: bold;">{}</span>', self.estado_actual, )
        
    
    def mostrar_imagen(self):
        if self.imagen:
            return format_html('<img src="{}" width="20" height="20">',self.imagen.url)
    
    def func_stock_valor(self):
        resultado = '{:,}'.format(self.precio * self.cantidad_disponible)
        return resultado

templates/store/models.py
from django.db import models
from django.utils.html import format_html


# Create your models here.


class Store(models.Model):

    no_pub = "No Publicado"
    pub = "Publicado"
    borr = "Borrador"
    ESTADO_PRODUCTO = (
        (no_pub, "No Publicado"),
        (pub, "Publicado"),
        (borr, "Borrador"),
    )

    filtro80 = "Filtro 80x80mm"
    filtro120 = "Filtro 120x120mm"
    filtro140 = "Filtro 140x140mm"
    hdd = "Disco Rigido"
    software = "Software"
    dir_lister = "Directories Lister"
    hm_meta = "Meta Data Extractor"
    LOS_PRODUCTOS = (
        (filtro80, "Filtro 80x80mm"),
        (filtro120, "Filtro 120x120mm"),
        (filtro140, "Filtro 140x140mm"),
        (hdd, "Disco Rigido"),
        (software, "Software"),
        (dir_lister, "Directories Lister"),
        (hm_meta, "Meta Data Extractor"),
    )



    producto = models.CharField(max_length=60, choices=LOS_PRODUCTOS)
    descripcion_corta = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=300)
    fecha_publicacion = models.DateField('Fecha de Publicacion')
    estado_actual = models.CharField(max_length=30, choices=ESTADO_PRODUCTO, default="No Publicado")
    precio = models.IntegerField("Precio AR$")
    cantidad_disponible = models.IntegerField('Unidades Disponibles')
    imagen = models.ImageField(upload_to="producto/%Y/%m/%d", blank=True, null=True) 
    stock_valor = models.IntegerField("Valor Stock AR$", null=True)
    
    # categoria = models.ManyToManyField(Categoria)

    def __str__(self):
        return str(self.producto) + " - " + str(self.cantidad_disponible) + " - "+ str(self.estado_actual)      #sobreescrito por list_display


    def tipo_de_estado(self):
        if self.estado_actual == "Publicado":
            return format_html('<span style="background-color: #31B404; padding: 2px; font-weight: bold;">{}</span>', self.estado_actual, )

        elif self.estado_actual == "Borrador":
            return format_html('<span style="background-color: #AEB404; padding: 2px; font-weight: bold;">{}</span>', self.estado_actual, )

        elif self.estado_actual == "No Publicado":
            return format_html('<span style="background-color: #FF0000; padding: 2px; font-weight: bold;">{}</span>', self.estado_actual, )
        
    
    def mostrar_imagen(self):
        if self.imagen:
            return format_html('<img src="{}" width="20" height="20">',self.imagen.url)
    
    def func_stock_valor(self):
        resultado = '{:,}'.format(self.precio * self.cantidad_disponible)
        return resultado

store/forms.py
from django.forms import ModelForm
from django import forms
from store.models import Store

class BuscarProductoForm(forms.Form):
    querycom = forms.CharField(label='Ingresar el nombre del producto a buscar', widget=forms.TextInput(attrs={'size': 32, 'class': 'form- control'}))
    
    
    
class CargarForm(ModelForm):
    class Meta:
        model = Store
        fields = ["producto", "fecha_publicacion", "imagen"]

        error_messages = {
            "producto": {
                "required": ("Se debe agregar un nombre de producto"),
            },
            "fecha_publicacion": {
                "required": (
                    "Se debe agregar la fecha de publicación en el formato adecuado"
                ),
            },
        }

    def __init__(self, *args, **kwargs):
        super(CargarForm, self).__init__(*args, **kwargs)

templates/store/forms.py
from django.forms import ModelForm
from django import forms
from store.models import Store

class BuscarProductoForm(forms.Form):
    querycom = forms.CharField(label='Ingresar el nombre del producto a buscar', widget=forms.TextInput(attrs={'size': 32, 'class': 'form- control'}))
    
    
    
class CargarForm(ModelForm):
    class Meta:
        model = Store
        fields = ["producto", "fecha_publicacion", "imagen"]

        error_messages = {
            "producto": {
                "required": ("Se debe agregar un nombre de producto"),
            },
            "fecha_publicacion": {
                "required": (
                    "Se debe agregar la fecha de publicación en el formato adecuado"
                ),
            },
        }

    def __init__(self, *args, **kwargs):
        super(CargarForm, self).__init__(*args, **kwargs)

store/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.http import HttpResponse
from .models import Store
from django.views.generic import View
from django.db.models import Q
from store.forms import BuscarProductoForm
import json
from django.contrib.auth.decorators import login_required


# Create your views here.


def index2(request):

    return HttpResponse("Store en construccion!!")

def index(request):
    params = {}
    params["site_name"] = "HM-NET Services"
    params["page_title"] = "Store"
    params['lista'] = "Una prueba par mandar algo desde views.py, va una lista: " + str(list(range(10)))
    params['productos_store'] = Store.objects.filter(Q(estado_actual="Publicado"))
    params['cantidad_total'] = Store.objects.count()
    #params["total_carro"] = ""
    temp = request.session.get("seleccion_productos")
    # if "total_carro" in request.session:
    #     params["total_carro"] = request.session["total_carro"]
        # return render(request, 'store/index.html', params)

    # else:
    #     params["total_carro"] = 0
    #     print("temp",temp)
    #     return render(request, 'store/index.html', params)
    return render(request, 'store/index.html', params)


def ver_imagen(request, producto_id):
    params={}
    try:
        producto = Store.objects.get(pk=producto_id)
    except producto.DoesNotExist:
        raise Http404
    params["producto"] = producto
    
    return render(request, "store/ver-producto.html", params)


class VerProducto(View):
    
    template = "store/ver-producto.html"
    
    
    def get(self, request, producto_id):
        
        params = {}
        producto = Store.objects.get(pk=producto_id)
        params['cantidad_total'] = Store.objects.count()
        params["producto"] = producto
        params["total_carro"] = ""
        temp = request.session.get("seleccion_productos")
        if temp:
            params["total_carro"] = request.session["total_carro"]
            
        return render(request, self.template, params)
    
    def post(self, request, producto_id):
        
        params = {}
        producto = request.POST.get("producto-seleccionado")
        seleccion_productos = request.session.get("seleccion_productos")
        #print(seleccion_productos)
        
        if seleccion_productos:
            cantidad = seleccion_productos.get(producto)
            
            if cantidad :
                seleccion_productos[producto] = cantidad + 1
            
            else:
                seleccion_productos[producto] = 1
        
        else:
            seleccion_productos = {}
            seleccion_productos[producto] = 1
            
        request.session["seleccion_productos"] = seleccion_productos
        total_carro = sum(seleccion_productos.values())
        request.session["total_carro"] = total_carro
        print(seleccion_productos)
        
        return redirect("/store/")


class VerProductoLs(View): 
    
    template = "store/ver-producto-ls.html"

    def get(self, request, producto_id):
        params={}
        try:
            producto = Store.objects.get(pk=producto_id)
        except Store.DoesNotExist:
            raise Http404
        params["producto"] = producto
        # ##########################################################
        # PARA INICIALIZAR LA VARIABLE DE SESSION CARRO
        # ###########################################################
        try:
            request.session["carro"]
            # request.session["total_carro"]
        except:
            request.session["carro"] = {}
            # request.session["total_carro"] = {}
        print("CARRO:", request.session["carro"])
        total_carro = sum(request.session["carro"].values())
        params["total_carro"] = total_carro
        print(params["producto"])    
        print("TOTALLLL CARRO", total_carro)
        return render(request, self.template, params)


# -----------------------------------------------------------------------------------------------
    #La clase barra_busqueda_ajax(request): tiene como url busqueda_ajax 
    #(no confundir con busqueda_ajax.html !!) al llamar a esta url definida en urls.py del store
    #llama al form BuscarProductoForm().
    #La clase BuscarProducto hace la consulta a la db apartir de los datos que 
    # vienen de la busqueda del form de busqueda_ajax.html, el js toma los datos 
    # con autocomplete, para el auto complete llama a la claseBuscarProducto quien 
    # hace la consulta a la db y devuelve los resultados en un json.dump que es lo 
    # que se muestra como resultados de busqueda, al hacer click en alguna de las 
    # opciones de busqueda que trae y al hacer click en el boton "ver datos" 
    # con id id="boton_prod" , llama y ejecuta la funcion onclick del static/js/ajax.js;
    # y el ajax llama a la clase BuscarProducto2 a travez de su url
    # (buscarproducto2, ver urls.py de store) quien le pasa la query a hacer por 
    # el prod seleccionado, la clase la hace, el ajax toma los resultados y se los pasa al 
    # html en el div contenedor_filtrado. Estoy casi segureo es asi pero chequear
    #
# -----------------------------------------------------------------------------------------------


def barra_busqueda_ajax(request):
    
    params = {}
    busqueda = BuscarProductoForm()
    params['busqueda'] = busqueda
    return render(request, 'store/busqueda_ajax.html', params)


class BuscarProducto(View):

    def get(self, request):
        if request.is_ajax:
            palabra_input = request.GET.get('term','')
            print("palabra innnnnnput",palabra_input)
            producto_ = Store.objects.filter(producto__icontains = palabra_input)
            resultado = []
            for i in producto_:
                data = {}
                data["label"] = i.producto
                resultado.append(data)
            data_json = json.dumps(resultado)
        else:
            data_json = "Error!"
        mimetype = "application/json"
        print("DDDATA JSONN",data_json)
        return HttpResponse(data_json, mimetype)
    
class BuscarProducto2(View):

    def get(self, request):
        print("hola")
        if request.is_ajax:
            q = request.GET['valor']

            print("111>>>>>>>>>>>> ", q)
            producto_ = Store.objects.filter(producto__icontains=q)
            print("222>>>>>>>>>>>> ",producto_)
            results = []
            for i in producto_:
                print(i.producto)
                print(i.estado_actual)
                print(i.imagen)


                data = {}
                data['producto'] = i.producto
                data['estado'] = i.estado_actual
                data['ruta_imagen'] = str(i.imagen)
                results.append(data)
          

            print("333>>>>>>>>>>>> ",results)
 
            data_json = json.dumps(results)
            mimetype = "application/json"
            return HttpResponse(data_json, mimetype)

    

templates/store/busqueda-ajax2.html
{% load static %}

<div class="container">
  <div class="row">
      <div class="col-12 prueba" style="padding-top:200px;">

      </div>
  </div>
</div>
<div class="container">
  <div class="row">
      <div class="col-12 prueba">
        <section id="todos_los_productos" class ="row" >
            <h2>Seleccionar producto aaaaaaaaaaaaaaaaaaaa</h2>
            <hr/>
            <div id="contenedor_filtros" class="row">
               <div id="filtros_productos"  class="col-xs-12">
                   <form id="searchr-form"   action="" method="post" >{% csrf_token  %}
                       <div class="campo_busqueda col-xs-12 "  >
                           {{ busqueda }}
                           <input type="button" id="boton_prod" value="Ver datos"/>
                       </div>
                    </form>
               </div>
            </div>
            <div id="contenedor_filtrado" class="col-xs-10 col-sm-offset-2 col-sm-8  
                                              col-md-offset-4 col-md-4 "></div>
        </section>
      </div>
  </div>
</div>
<div class="container">
<div class="row">
    <div class="col-12 prueba" style="padding-bottom: 250px;">
       
    </div>
</div>
</div>
  <div class="container">
      <div class="row">
          <div class="col-12 prueba" style="padding-top:200px;">
 
          </div>
      </div>
</div>

{% comment %} <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>  {% endcomment %}
<script type="text/javascript" src="{% static 'js/ajax.js' %}"></script>
<script type="text/javascript">
    $(' #id_querycom ').autocomplete({source:"/store/buscar_producto/"});
</script>

templates/store/busqueda_ajax.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<div class="container">
  <div class="row">
      <div class="col-12 prueba" style="padding-top:200px;">

      </div>
  </div>
</div>
<div class="container">
  <div class="row">
      <div class="col-12 prueba">
        <section id="todos_los_productos" class ="row" >
            <h2>Seleccionar productossssssssssssssssssss</h2>
            <hr/>
            <div id="contenedor_filtros" class="row">
               <div id="filtros_productos"  class="col-xs-12">
                   <form id="searchr-form"   action="" method="post" >{% csrf_token  %}
                       <div class="campo_busqueda col-xs-12 "  >
                           {{ busqueda }}
                           <input type="button" id="boton_prod" value="Ver datos"/>
                       </div>
                    </form>
               </div>
            </div>
            <div id="contenedor_filtrado" class="col-xs-10 col-sm-offset-2 col-sm-8  
                                              col-md-offset-4 col-md-4 "></div>
        </section>
      </div>
  </div>
</div>
<div class="container">
<div class="row">
    <div class="col-12 prueba" style="padding-bottom: 250px;">
       
    </div>
</div>
</div>
  <div class="container">
      <div class="row">
          <div class="col-12 prueba" style="padding-top:200px;">
 
          </div>
      </div>
</div>

{% block scripts %}
{% comment %} <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/ajax.js' %}"></script> {% endcomment %}
<script
src="https://code.jquery.com/jquery-3.6.4.min.js"
integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8="
crossorigin="anonymous">
</script>
<script
src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"
integrity="sha256-lSjKY0/srUM9BE3dPm+c4fBo1dky2v27Gdjm2uoZaL0="
crossorigin="anonymous">
</script>
<script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
{% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>  {% endcomment %}
<script type="text/javascript" src="{% static 'js/ajax.js' %}"></script>
<script>
  $('#id_querycom').autocomplete({source:"/store/buscar_producto/"});
</script>


{% endblock %}

{% endblock %}

templates/store/index copy.html
{% extends "layout.html" %}
{% load static %}

{% block body %}

<h1 class="text-center">HM-NET Store</h1>
<h4 class="text-center">Un subtitulo H4 lalalal</h4>
<div class="fluid py-3">
  <div class="card" style="background-color: antiquewhite;">
    <div class="card-body">
        <div class="row row-cols-1 row-cols-md-2 g-4">
          {% for p in productos_store %}
            <div class="col py-2">
              <div class="card">
                <img src="/media/{{p.imagen}}" class="img-thumbnail" alt="...">
                <div class="card-body">
                  <h5 class="card-title">{{p.producto}}</h5>
                  <p class="card-text">{{p.descripcion}}</p>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
    </div>
  </div>
</div>

{% endblock %}

templates/store/index.html
{% extends "layout.html" %}
{% load static %}

{% block body %}


<!-- Section-->
<section class="py-5">
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <i class="fa-solid fa-triangle-exclamation fa-bounce"></i><strong> {{message}}</strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
  <div class="container-fluid">
      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for p in productos_store %}
        {% comment %}         
        {% if p.estado_actual == "Publicado" %}
        {% endcomment %}
        <div class="col mb-5">
              <div class="card h-100">
                  <!-- Product image-->
                  <img class="card-img-top" src="/media/{{p.imagen}}" alt="..." />
                  <!-- Product details-->
                  <div class="card-body fluid p-1">
                      <div class="text-center">
                          <!-- Product name-->
                          <h5 class="fw-bolder">{{p.producto}}</h5>
                          <div class="d-flex justify-content-center small text-warning mb-1">
                            <div class="bi-star-fill">★</div>
                            <div class="bi-star-fill">★</div>
                            <div class="bi-star-fill">★</div>
                            <div class="bi-star-fill">★</div>
                          </div>
                          <p><a class="fw-bolder" style="font-size: small;">{{p.descripcion_corta}}</a></p>
                          
                          <!-- Product price-->
                          ${{p.precio}}
                        </div>
                    </div>
                  <!-- Product actions-->
                  <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    {% comment %} {% if request.user.is_authenticated %} {% endcomment %}
                      <div class="text-center"><a class="btn btn-outline-dark mt-auto" style="background-color:#25A2C7" href="{% url 'ver-producto-ls' producto_id=p.id %}">Ver Mas</a></div>
                    {% comment %} {% else %}
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" style="background-color:#898ED9" href="{% url 'login' %}">Ver Mas</a></div>
                    {% endif %} {% endcomment %}
                  </div>
                  
              </div>
        </div>
      {% comment %} {% else %} {% endcomment %}
      {% comment %} {% endif %} {% endcomment %}
      {% endfor %}  
      </div>
  </div>
</section>

{% endblock %}

templates/store/ver-producto copy.html
{% extends "layout.html" %}
{% load static %}

{% block body %}


<!-- Section-->
{% if producto.estado_actual == "Publicado" %}
<section class="py-5">
  <div class="container px-4 px-lg-5 my-5" style="background-color:#FFFFFF;">
    <br>
      <div class="row gx-4 gx-lg-5 align-items-center">
          <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="/media/{{producto.imagen}}" alt="..." /></div>
          <div class="col-md-6" style="background-color:#FFFFFF;">
              <div class="small mb-1">SKU: BST-498</div>
              <h1 class="display-5 fw-bolder">{{producto.producto}}</h1>
              <div class="fs-5 mb-5">
                  {% comment %} <span class="text-decoration-line-through">{{producto.precio}}</span> {% endcomment %}
                  <span>${{producto.precio}}</span>
              </div>
              <p class="lead">{{producto.descripcion}}</p>
              <div class="d-flex">
                  <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                  <button class="btn btn-outline-dark flex-shrink-0" type="button">
                      <i class="bi-cart-fill me-1"></i>
                      <a href="{% url 'store_index' %}">Agregar al carrito</a>
                  </button>
              </div>
          </div>
      </div>
      <br>
  </div>
  <div class="container px-4 px-lg-5 my-5">
    <div class="col text-center">
      <div class="text-center"><a class="btn btn-outline-dark mt-auto" style="background-color:#D8D5D5;" href="{% url 'store_index' %}">Volver</a>
    </div>
  </div>
</section>

<!-- Related items section-->

</section>
      {% else %}
      {% endif %}

{% endblock %}

templates/store/ver-producto.html
{% extends "layout.html" %}
{% load static %}

{% block body %}


<!-- Section-->
{% if producto.estado_actual == "Publicado" %}
<section class="py-5">
  <div class="container px-4 px-lg-5 my-5" style="background-color:#FFFFFF;">
    <br>
      <div class="row gx-4 gx-lg-5 align-items-center">
          <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="/media/{{producto.imagen}}" alt="..." /></div>
          <div class="col-md-6" style="background-color:#FFFFFF;">
              <div class="small mb-1">SKU: BST-498</div>
              <h1 class="display-5 fw-bolder">{{producto.producto}}</h1>
              <div class="fs-5 mb-5">
                  {% comment %} <span class="text-decoration-line-through">{{producto.precio}}</span> {% endcomment %}
                  <span>${{producto.precio}}</span>
              </div>
              <p class="lead">{{producto.descripcion}}</p>
              <div class="d-flex">
                  <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                  <form action="/store/{{producto.id}}/ver/" method="post">{% csrf_token %}
                    <input hidden type="text" name="producto-seleccionado" value="{{producto.id}}"/>
                    <input type="submit" button class="btn btn-outline-dark flex-shrink-0" type="button" value="Agregar al carrito"/>
                  </form>
                      <i class="bi-cart-fill me-1"></i>
                      {% comment %} <a href="{% url 'store_index' %}">Agregar al carrito</a> {% endcomment %}
                  {% comment %} </button> {% endcomment %}
              </div>
          </div>
      </div>
      <br>
  </div>
  <div class="container px-4 px-lg-5 my-5">
    <div class="col text-center">
      <div class="text-center"><a class="btn btn-outline-dark mt-auto" style="background-color:#D8D5D5;" href="{% url 'store_index' %}">Volver</a>
    </div>
  </div>
</section>

<!-- Related items section-->

</section>
      {% else %}
      {% endif %}

{% endblock %}

templates/store/ver-producto_.html
{% extends "layout_store.html" %}
{% load static %}

{% block body %}


<!-- Section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% if producto.estado_actual == "Publicado" %}
        <div class="col mb-5">
              <div class="card h-100">
                  <!-- Product image-->
                  <img class="card-img-top" src="/media/{{producto.imagen}}" alt="..." />
                  <!-- Product details-->
                  <div class="card-body p-4">
                      <div class="text-center">
                          <!-- Product name-->
                          <h5 class="fw-bolder">{{producto.producto}}</h5>
                          <div class="d-flex justify-content-center small text-warning mb-2">
                            <div class="bi-star-fill">★</div>
                            <div class="bi-star-fill">★</div>
                            <div class="bi-star-fill">★</div>
                            <div class="bi-star-fill">★</div>
                          </div>
                          <p><a class="fw-bolder" style="font-size: small;">{{producto.descripcion}}</a></p>
                          
                          <!-- Product price-->
                          ${{producto.precio}}
                        </div>
                    </div>
                  <!-- Product actions-->
                  <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                      <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Agregar al carrito</a></div>
                  </div>
              </div>
        </div>
      {% else %}
      {% endif %}

      </div>
  </div>
</section>
{% endblock %}